[tools]
tailwindcss = "4.2.2"
wasm_bindgen = "0.2.117"
wasm_opt = "version_129"

[build]
minify = "on_release"

[watch]
ignore = ["js-reexport/dist/reexports.js"]

[[hooks]]
stage = "pre_build"
command = "npm"
command_arguments = ["--prefix=js-reexport", "run", "build"]
